import java.io.File
import java.nio.file.Files
import java.security.MessageDigest

group 'com.alexmercerind.media_kit_libs_android_video'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    // Conditional for compatibility with AGP <4.2.
    if (project.android.hasProperty("namespace")) {
        namespace 'com.alexmercerind.media_kit_libs_android_video'
    }

    compileSdkVersion 31

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 16
    }

    dependencies {
        implementation fileTree(dir: "$buildDir/output", include: "*.jar")
    }
}

task downloadDependencies(type: Exec) {   
        // Delete previously created /output subdirectory.

        def outputDir = file("$buildDir/output")
        if (outputDir.exists()) {
            outputDir.deleteDir()
        }
        outputDir.mkdirs()

        // Download all *.jar dependencies & verify their SHA-256 checksums.
        def filesToDownload = [
            ["url": "https://github.com/archive-user/libmpv-android-video-build/releases/download/1.0.8/default-arm64-v8a.jar", "sha256": "75e60018cb37f9d1b5dd0ca24e117ff0ecd14c70eb9bd0570574c042cf6344a6", "destination": file("$buildDir/1.0.8/default-arm64-v8a.jar")],
            ["url": "https://github.com/archive-user/libmpv-android-video-build/releases/download/1.0.8/default-armeabi-v7a.jar", "sha256": "c304bdc202033660d006658788272c23fb66201443eae1c996a2f587c8298ddb", "destination": file("$buildDir/1.0.8/default-armeabi-v7a.jar")],
            ["url": "https://github.com/archive-user/libmpv-android-video-build/releases/download/1.0.8/default-x86_64.jar", "sha256": "110f1d09976e52dd1ec78381f7525a474ac7458683df32bffb462dee66a88c5b", "destination": file("$buildDir/1.0.8/default-x86_64.jar")],
            ["url": "https://github.com/archive-user/libmpv-android-video-build/releases/download/1.0.8/default-x86.jar", "sha256": "fa944b123c1cda76a7e3e388c5370260f9495b7577663fee80dd684fc34bbe3d", "destination": file("$buildDir/1.0.8/default-x86.jar")]
        ]

        filesToDownload.each { fileInfo ->
            def destFile = fileInfo.destination
            if (destFile.exists()) {
                def calculatedSHA256 = MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(destFile.toPath())).encodeHex().toString()

                if (calculatedSHA256 != fileInfo.sha256) {
                    destFile.delete()
                    println "SHA-256 mismatch. File deleted: ${destFile}"
                }

            }

            if (!destFile.exists()) {
                destFile.parentFile.mkdirs()
                println "Downloading file from: ${fileInfo.url}"
                destFile.withOutputStream { os ->
                    os << new URL(fileInfo.url).openStream()
                }

                def calculatedSHA256 = MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(destFile.toPath())).encodeHex().toString()
                if (calculatedSHA256 != fileInfo.sha256) {
                    throw new GradleException("SHA-256 verification failed for ${destFile}")
                }
            }

            copy {
                from destFile
                into outputDir
            }
        }
}

assemble.dependsOn(downloadDependencies)